language: python
python:
- '2.7'
before_install:
- psql -c 'create database travis_ci_test;' -U postgres
- export DATABASE_URL=postgresql:///travis_ci_test
- gem install foreman
install: pip install -r requirements.txt --use-mirrors
script: python test_server.py
deploy:
  provider: heroku
  api_key:
    secure: cxkeI3OinsMwH/KPGojgR4fCxpYYEffKZX9bR6DRexfJxB4nCg5yAyzvTsLYw3TKUFPeFFWAWhcRLl1N1l/mJyqMxtSBcYIIwaCP3brADlj4HRSt7LUF+vhUcrwC4pg+wwCqWQW/r8cHlZPjUY4q+tyA76a9y3Kt4Av9qkjj1+Y=
  app: lespi-server
  strategy: git
