language: python
python:
- '2.7'
before_install:
- psql -c 'create database travis_ci_test;' -U postgres
- export DATABASE_URL=postgresql:///travis_ci_test
- gem install foreman
install: pip install -r requirements.txt --use-mirrors
script: python test_server.py
deploy:
  provider: heroku
  api_key:
    secure: fKhh5eLlJKVS7zJhF0toXHCJjqXfUEufWrj5xuzUl1dbNx28NhkuXpX/ix9PzqYefzeTCtmPf6aNxW9X6aKbupDT/5XQCte5Q/TW52E1j4KxT4QaqAoW9fCeKc0bJZ7Yuq2vAnj5dfCpc5oOJoq8cunk0Spsnh8tsVF+e8VMOcQ=
  app: lespi-server
  strategy: git
