language: python
python:
- '2.7'
before_install:
- psql -c 'create database travis_ci_test;' -U postgres
- export DATABASE_URL=postgresql:///travis_ci_test
- gem install foreman
install: pip install -r requirements.txt --use-mirrors
script: python test_server.py
deploy:
  provider: heroku
  api_key:
    secure: fKhh5eLlJKVS7zJhF0toXHCJjqXfUEufWrj5xuzUl1dbNx28NhkuXpX/ix9PzqYefzeTCtmPf6aNxW9X6aKbupDT/5XQCte5Q/TW52E1j4KxT4QaqAoW9fCeKc0bJZ7Yuq2vAnj5dfCpc5oOJoq8cunk0Spsnh8tsVF+e8VMOcQ=
  app: lespi-server
  strategy: git
env:
  global:
  - secure: HaE3cCkLOVJm6AG+Dx8zTXMq8di7vvbwSur+CZTQQTpZ0vjhDi2wmJjolVlgZzV9i3lJCcbE763i3ZiN45gZYO6WWjPziBHIH1lRq8p3BiaYTv6Nu672n5c/s7Cw1Uo638b/mG8XMWIbXuIGPx8BOAakBSTbEv0D306hwN/CDJw=
  - secure: Rtc95W9EdL5r73MIXWRYSfL9f6zJPeijRAcZYhLK7bzfYzesTkEN7OqyCHY1nL871v0kR9jSZfV4iARb6Hkri6Yc6pj/mbVbqAVoGIVvv9NAoX/AU6CR48pBMAV0ULlvIO3SEO9gkGy+u6LkEzN1IBHwGih3LHZ0bnZ3qhXSJnM=
  - secure: ObFBSm7bfe3x2/9xMwC2CKUU00fyApOS4MYTRTX9As4Bb6uAGsA+nQUIJFSW0XqSdRo8sQtiBbP9muj2hSSNYAf4z/AgWj3nnGgyygisG8uKMuJNKkCgREPLdgidFUHMHvakfuVYvnwgR4IFtBzU0XgDojjQoqzPRvJgBBapPuQ=
  - secure: PimuLm6sEJs1/DUWDp9Tz6Jq8GPQCk2MVsCv06o6Su/4e1dTZLZFzwqMZvcSiLNBy9pPNcU55EW0AUY5CdRod5uzKl2MUobYlepH9JMEipgfWk5WTtSEsQOhfQKCQcpCFpFN6Empj2NF5XGBoEkgE9K/jTkR/rF7TUX5SmefHr0=
  - secure: M+Z01QJ+KAT2xbK/7u6Sris6BrY24cprQapAkKPxNcLn8DgSozeIxfcp//Kt2hCPiJNCHKlj06EIn9gX3zMkJEvkbR2jNWqKIbJiFmR//aRp1BzJFl5BTw7aWunbGQLZNavhiKlM+F4OGhgfOjiyvfN2cHE9o2YRxIsYizqC7Bo=
  - secure: mhxuv+whx+i88K4Dshcn7txYxSyuQh3WEsN/wcsHOmH9uqpNcSbBPwwtGYqhPRxT+EoHmZcsaehcjEMrBSVvGnYT6+CUjfR2OY77WR5V6o3yIIgy2pLW2YOoHiiGmcHn7yKzRm5cYkCHLsCtzJcPsOu/xpXRZ10fwJpGb2a+KFI=
