language: python
python:
- '2.7'
before_install:
- psql -c 'create database travis_ci_test;' -U postgres
- export DATABASE_URL=postgresql:///travis_ci_test
- gem install foreman
install: pip install -r requirements.txt --use-mirrors
script: python test_server.py
deploy:
  provider: heroku
  api_key:
    secure: fKhh5eLlJKVS7zJhF0toXHCJjqXfUEufWrj5xuzUl1dbNx28NhkuXpX/ix9PzqYefzeTCtmPf6aNxW9X6aKbupDT/5XQCte5Q/TW52E1j4KxT4QaqAoW9fCeKc0bJZ7Yuq2vAnj5dfCpc5oOJoq8cunk0Spsnh8tsVF+e8VMOcQ=
  app: lespi-server
  strategy: git
env:
  global:
  - secure: ZNiRMgbOGPlGyeI3EfX7ER+7l+axdaeK1p3+5biIKHBTgpoQIjFUSX+y5YQHC0BFYhpbs3tWt/L5rejcMio/fRBsFxer6fHUroLwoaCjR3505XOi0c3yl3HSNJh3tea6El6In51HVp3BJ5i11UgCcueZWp3Zqznfa4SnhV/PMBc=
  - secure: UXTePT3HqLG31f6SedhFr5MuOhc9TGgA4ThX6q5MHAGQj/jgT3ONq2G02d0o3qH0B6WmBPH5k7SAYluzXi+j4Fh+suO2awtHyY//ovuW4SVBsTd/DHbpbOhbUS2DrB/gVcHYHlQSeDBxGLr1Pv7svK32yEfOjdArKFuhwMrb3MM=
  - secure: Txi1XdSUpwabnuXnoH2xOZFu6qIwBrqk049jNR08rlibxZKq5wlgpoe2cTSli1Kzh9Jk4ixlp0a6pJY7ZmbZtkEt1sjFWLE1G0Mgv+onP8gO/D45FaegsYTaMZvT8EgLyfFsEmBR3GK87VSNVyBAih5wRe9B7Sj3ABuCGrW8L84=
  - secure: A/IZ8HyW74ykEjsApMvUv+GySZIuK54GhCoJacU4Ix/CTizgt9W5roKtbTVH5O7sYYxXMnqNSPHY80Pr+seaY1/FHE8rpmkYfteSIb2ixeNlfF6aQRM6kUy+OksVGhXuXryAHFGxSPJ53xazXaNP3YkG/mAcWZVqVvKqH/XPhlc=
  - secure: SGqTLFAqRr37PpqpIq+lvLi2QhC0B9+UCPQ8F/0HcDvKBb5F24Y9iWhZ86gUSL5rRJ4+7/cTQs421DeFeiOiQARAjeNBcMvqzLIKoMbiNXThAdOwnM9pzAk8Jp0B5z0qQuiqHnq84GVZoLUhHjXauuslZ/0kWbBrbYqu0FlUnZw=
  - secure: AE5dAdSF/6IUgHXKN5kpA3NOZ9d6BMUnGTQFRPqxlmq9GVGhg2yA1jhDYYfFb2P/p6b30FRccrSzypUsCvZyn8EkaZnq7+4x+/2dnCBxwXZDNdMe3iYtVSTL1qkitiyV66cDaCrSOb5M+uqRvCpWoD3BQywViR8ZDliTi4tOWwo=
  - secure: bKE/B02CuM9dK4kXEFXt+RilHLhwVCLLUVFjgwtrPS5LtzamhduCn+OaUJPd4hIX87W0blV81gmS/q+yk/DEj0QKDLw6OehHGXd2qU3UIQdrIb2Z1n1YCZA2DeEQmRa9cpUGtdASJThIjQIqUztY830m/mB4u2Tal8k3LpI6KMo=
  - secure: NZc45rvGKiDrArfYvum3QOSaBoeq6epnoXXs1YsM5Y9nBXB9zLtjybDzfiW2K8tzoUlQqTVveLg5EwyHv3Jka2GArvntNAA0Bbb6Od4C2OOa12jH7mfZto31L4qhQfBr0NTmTjg/Iv2D8RwZjSYYLG1bTlMNUkUV4o2+NZzvMDg=
  - secure: nqLpdJH6+T/A+DiUZraqZclm2raO150/+A/pSJJyCSbYP1RrJmSjR/JK6qPuFu8EyF1Ka947DUZFmeR+nGOyaentOMCD3jbF9SGRAQNQR9o0QLdUsaFSWLwzun0/ZlK5KIJ5lkI/kThvAbYXbG4UMWVjfJrNVkqOkyeQjp4ZsDk=
  - secure: ZXeds4n9lBlc6ccigsrXDsYn1QTsV7rpUS1F7jUQuDLIUBnVySMGoWIArHJhwKUKBh5wO+kZgDZsQuqpa2JMglIzDJPs9mDrF4GW1Bzyqo7HLHnJctjbQi27NbHKkAXg/AqKkrLF6FbUD3tVY9pKl+I7SzJDPrGc7GQjhYxbRPA=
